version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapea el puerto 8080 del contenedor al host
    environment:
      SPRING_PROFILES_ACTIVE: docker # Usa un perfil Docker si necesitas configuraciones específicas

